server:
  port: 8080

# DEV Log file path
file:
  path: dev/custom-logfile-${spring.profiles.active}-%d{yy-MM-dd_HH-mm}.%i.log

# H2 Database settings
spring:
  h2:
    console:
      enabled: true
      path: /h2-console

datasource:
  url: jdbc:h2:mem:dcbapp
  driverClassName: org.h2.Driver
  username: sa
  password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: true

management:
  endpoints:
    web:
      exposure:
        include: env, info

  # JWT secret key and validity settings---
jwt:
  secretKey: secestskjdhsdhskdjhsakjdhsakdjhsriuewyrewiuryweiurwyerhkfjhsdfkjdsheiuowryweiurhfjdsnfsdmnfksdjfhds
validity: 3600000  # Make sure this is properly indented under 'jwt'

# OpenAPI (SpringDoc) settings
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
